% -------------------------------------------------------------------
%  Generated by MATLAB on 28-Oct-2022 20:41:05
%  MATLAB version: 9.8.0.1323502 (R2020a)
% -------------------------------------------------------------------

% Load the variables from the 'tfFile.mat' file into the workspace
saveVarsMat = load('tfFile.mat');

% Define system parameters
ETAtot_Kt = 1.8;        % Total efficiency coefficient
Kb = 2;                 % Gain constant
Kcs = 0.5;              % Controller gain
Kf = 0.1;               % Feedback gain
Kss = 0.0433;           % Steady-state gain
PCwAvor_Itot = 0.6154;  % Total power coefficient
Ra_inv = 1;             % Inverse resistance
r_Itot = 0.0615;        % Total resistance

% Extract the state-space representation of the system from the loaded data
linsys1 = saveVarsMat.linsys1; % <1x1 ss> unsupported class

% Extract the transfer function from the loaded data
tfFun = saveVarsMat.tfFun; % <1x1 tf> unsupported class

% Clear the loaded variable structure to free up memory
clear saveVarsMat;